In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
from datetime import datetime, timedelta, timezone

import polars as pl

from backtester import io, samplers
from backtester.dtypes import SpotInstrument, OptionInstrument

## Sample data

In [3]:
t0 = datetime(2025, 1, 1, tzinfo=timezone.utc)
tf = datetime(2025, 3, 31, tzinfo=timezone.utc)
dt = timedelta(hours=1)

In [4]:
lf_rate = samplers.get_path_rate(t0, tf, dt)
paths_mark = samplers.get_paths_mark(t0, tf, dt, names=["btc"], s0=[100_000], mu=[0.10], sigma=[0.50])
lf_spot = samplers.to_bars_spot(paths_mark, exchanges="drbt", quotes="usd")
lf_option = samplers.to_bars_option(paths_mark, "drbt", "btc", "usd", rules=[samplers._WEEKLY])

In [5]:
lf_rate.collect()

shape: (2_136, 3)
┌─────────────────────────┬─────────────────────────┬──────────┐
│ time_start              ┆ time_end                ┆ rate     │
│ ---                     ┆ ---                     ┆ ---      │
│ datetime[μs, UTC]       ┆ datetime[μs, UTC]       ┆ f64      │
╞═════════════════════════╪═════════════════════════╪══════════╡
│ 2025-01-01 00:00:00 UTC ┆ 2025-01-01 01:00:00 UTC ┆ 0.05     │
│ 2025-01-01 01:00:00 UTC ┆ 2025-01-01 02:00:00 UTC ┆ 0.050149 │
│ 2025-01-01 02:00:00 UTC ┆ 2025-01-01 03:00:00 UTC ┆ 0.049953 │
│ 2025-01-01 03:00:00 UTC ┆ 2025-01-01 04:00:00 UTC ┆ 0.050049 │
│ 2025-01-01 04:00:00 UTC ┆ 2025-01-01 05:00:00 UTC ┆ 0.049847 │
│ …                       ┆ …                       ┆ …        │
│ 2025-03-30 19:00:00 UTC ┆ 2025-03-30 20:00:00 UTC ┆ 0.047558 │
│ 2025-03-30 20:00:00 UTC ┆ 2025-03-30 21:00:00 UTC ┆ 0.047537 │
│ 2025-03-30 21:00:00 UTC ┆ 2025-03-30 22:00:00 UTC ┆ 0.04748  │
│ 2025-03-30 22:00:00 UTC ┆ 2025-03-30 23:00:00 UTC ┆ 0.047588 │
│ 2025-03-30 23:00:00 UTC ┆ 2025-03-31 00:00:00 UTC ┆ 0.047638 │
└─────────────────────────┴─────────────────────────┴──────────┘

In [6]:
lf_spot.collect()

shape: (2_136, 8)
┌──────────────┬──────────────┬──────┬──────────────┬──────────┬───────┬─────────────┬─────────────┐
│ time_start   ┆ time_end     ┆ base ┆ px_mark      ┆ exchange ┆ quote ┆ px_bid      ┆ px_ask      │
│ ---          ┆ ---          ┆ ---  ┆ ---          ┆ ---      ┆ ---   ┆ ---         ┆ ---         │
│ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64          ┆ str      ┆ str   ┆ f64         ┆ f64         │
│ UTC]         ┆ UTC]         ┆      ┆              ┆          ┆       ┆             ┆             │
╞══════════════╪══════════════╪══════╪══════════════╪══════════╪═══════╪═════════════╪═════════════╡
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 100673.71020 ┆ drbt     ┆ usd   ┆ 99666.97310 ┆ 101680.4473 │
│ 00:00:00 UTC ┆ 01:00:00 UTC ┆      ┆ 5            ┆          ┆       ┆ 3           ┆ 07          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99951.627551 ┆ drbt     ┆ usd   ┆ 98952.11127 ┆ 100951.1438 │
│ 01:00:00 UTC ┆ 02:00:00 UTC ┆      ┆              ┆          ┆       ┆ 6           ┆ 27          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99308.625518 ┆ drbt     ┆ usd   ┆ 98315.53926 ┆ 100301.7117 │
│ 02:00:00 UTC ┆ 03:00:00 UTC ┆      ┆              ┆          ┆       ┆ 3           ┆ 73          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99450.223732 ┆ drbt     ┆ usd   ┆ 98455.72149 ┆ 100444.7259 │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆      ┆              ┆          ┆       ┆ 5           ┆ 69          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99580.563351 ┆ drbt     ┆ usd   ┆ 98584.75771 ┆ 100576.3689 │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 85          │
│ …            ┆ …            ┆ …    ┆ …            ┆ …        ┆ …     ┆ …           ┆ …           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 120682.67144 ┆ drbt     ┆ usd   ┆ 119475.8447 ┆ 121889.4981 │
│ 19:00:00 UTC ┆ 20:00:00 UTC ┆      ┆ 5            ┆          ┆       ┆ 31          ┆ 6           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 120408.70239 ┆ drbt     ┆ usd   ┆ 119204.6153 ┆ 121612.7894 │
│ 20:00:00 UTC ┆ 21:00:00 UTC ┆      ┆              ┆          ┆       ┆ 66          ┆ 14          │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 120146.76700 ┆ drbt     ┆ usd   ┆ 118945.2993 ┆ 121348.2346 │
│ 21:00:00 UTC ┆ 22:00:00 UTC ┆      ┆ 4            ┆          ┆       ┆ 34          ┆ 74          │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 119431.52657 ┆ drbt     ┆ usd   ┆ 118237.2113 ┆ 120625.8418 │
│ 22:00:00 UTC ┆ 23:00:00 UTC ┆      ┆ 7            ┆          ┆       ┆ 11          ┆ 42          │
│ 2025-03-30   ┆ 2025-03-31   ┆ btc  ┆ 119235.83369 ┆ drbt     ┆ usd   ┆ 118043.4753 ┆ 120428.1920 │
│ 23:00:00 UTC ┆ 00:00:00 UTC ┆      ┆ 4            ┆          ┆       ┆ 57          ┆ 31          │
└──────────────┴──────────────┴──────┴──────────────┴──────────┴───────┴─────────────┴─────────────┘

In [7]:
lf_option.collect()

shape: (20_800, 12)
┌────────────────────┬────────────────────┬──────────┬──────┬───┬──────┬────────┬────────┬─────────┐
│ time_start         ┆ time_end           ┆ exchange ┆ base ┆ … ┆ kind ┆ iv_bid ┆ iv_ask ┆ iv_mark │
│ ---                ┆ ---                ┆ ---      ┆ ---  ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---     │
│ datetime[μs, UTC]  ┆ datetime[μs, UTC]  ┆ str      ┆ str  ┆   ┆ str  ┆ f64    ┆ f64    ┆ f64     │
╞════════════════════╪════════════════════╪══════════╪══════╪═══╪══════╪════════╪════════╪═════════╡
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 08:00:00 UTC       ┆ 09:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 09:00:00 UTC       ┆ 10:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 10:00:00 UTC       ┆ 11:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 11:00:00 UTC       ┆ 12:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 12:00:00 UTC       ┆ 13:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ …                  ┆ …                  ┆ …        ┆ …    ┆ … ┆ …    ┆ …      ┆ …      ┆ …       │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 19:00:00 UTC       ┆ 20:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 20:00:00 UTC       ┆ 21:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 21:00:00 UTC       ┆ 22:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 22:00:00 UTC       ┆ 23:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-31         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 23:00:00 UTC       ┆ 00:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
└────────────────────┴────────────────────┴──────────┴──────┴───┴──────┴────────┴────────┴─────────┘

## `_get_lf_priced`

In [9]:
lf_priced = io._build_lf_priced(
    lf_rate, lf_spot, lf_option,
    option_exchange="drbt",
    option_base="btc",
    option_quote="usd",
    spot_exchange="drbt",
    spot_base="btc",
    spot_quote="usd",
)
lf_priced.collect()

shape: (20_800, 22)
┌─────────────┬────────────┬──────────┬──────┬───┬──────────┬────────────┬────────────┬────────────┐
│ time_start  ┆ time_end   ┆ exchange ┆ base ┆ … ┆ gamma    ┆ vega       ┆ theta      ┆ rho        │
│ ---         ┆ ---        ┆ ---      ┆ ---  ┆   ┆ ---      ┆ ---        ┆ ---        ┆ ---        │
│ datetime[μs ┆ datetime[μ ┆ str      ┆ str  ┆   ┆ f64      ┆ f64        ┆ f64        ┆ f64        │
│ , UTC]      ┆ s, UTC]    ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
╞═════════════╪════════════╪══════════╪══════╪═══╪══════════╪════════════╪════════════╪════════════╡
│ 2025-03-30  ┆ 2025-03-31 ┆ drbt     ┆ btc  ┆ … ┆ 0.000012 ┆ 1907.98844 ┆ -80784.179 ┆ 106.179976 │
│ 23:00:00    ┆ 00:00:00   ┆          ┆      ┆   ┆          ┆ 5          ┆ 954        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000011 ┆ 1981.27059 ┆ -83093.979 ┆ 111.845899 │
│ 22:00:00    ┆ 23:00:00   ┆          ┆      ┆   ┆          ┆ 3          ┆ 085        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000012 ┆ 2177.13994 ┆ -90461.997 ┆ 126.864962 │
│ 21:00:00    ┆ 22:00:00   ┆          ┆      ┆   ┆          ┆ 7          ┆ 97         ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000013 ┆ 2270.01258 ┆ -93448.632 ┆ 134.462121 │
│ 20:00:00    ┆ 21:00:00   ┆          ┆      ┆   ┆          ┆ 2          ┆ 699        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000013 ┆ 2367.04914 ┆ -96550.467 ┆ 142.57291  │
│ 19:00:00    ┆ 20:00:00   ┆          ┆      ┆   ┆          ┆ 3          ┆ 264        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ …           ┆ …          ┆ …        ┆ …    ┆ … ┆ …        ┆ …          ┆ …          ┆ …          │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000011 ┆ 1955.37884 ┆ -52133.018 ┆ -151.82579 │
│ 12:00:00    ┆ 13:00:00   ┆          ┆      ┆   ┆          ┆ 8          ┆ 406        ┆ 7          │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.00001  ┆ 1865.66879 ┆ -49442.434 ┆ -142.70678 │
│ 11:00:00    ┆ 12:00:00   ┆          ┆      ┆   ┆          ┆ 2          ┆ 203        ┆ 3          │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000009 ┆ 1791.24518 ┆ -47186.017 ┆ -135.36300 │
│ 10:00:00    ┆ 11:00:00   ┆          ┆      ┆   ┆          ┆ 1          ┆ 495        ┆ 6          │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000009 ┆ 1644.58639 ┆ -43070.088 ┆ -121.08134 │
│ 09:00:00    ┆ 10:00:00   ┆          ┆      ┆   ┆          ┆ 5          ┆ 629        ┆ 5          │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000009 ┆ 1734.51322 ┆ -45149.034 ┆ -130.18891 │
│ 08:00:00    ┆ 09:00:00   ┆          ┆      ┆   ┆          ┆ 6          ┆ 877        ┆ 5          │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
└─────────────┴────────────┴──────────┴──────┴───┴──────────┴────────────┴────────────┴────────────┘

In [10]:
# Sanity checks: prices positive, Greeks finite
df_priced = lf_priced.collect()
assert (df_priced["px_mark"] >= 0).all(), "px_mark should be non-negative"
assert df_priced["delta"].is_finite().all(), "delta should be finite"
assert df_priced["gamma"].is_finite().all(), "gamma should be finite"
assert df_priced["vega"].is_finite().all(), "vega should be finite"
assert df_priced["theta"].is_finite().all(), "theta should be finite"
assert df_priced["rho"].is_finite().all(), "rho should be finite"
print(f"priced rows: {len(df_priced):,}")

priced rows: 20,800

In [11]:
df_priced.filter(pl.col("px_mark") <= 0).select([
    "time_start", "time_end", "exchange", "base", "quote", "strike", "listing", "expiry", "kind", "px_mark"
])

shape: (245, 10)
┌──────────────┬──────────────┬──────────┬──────┬───┬──────────────┬──────────────┬──────┬─────────┐
│ time_start   ┆ time_end     ┆ exchange ┆ base ┆ … ┆ listing      ┆ expiry       ┆ kind ┆ px_mark │
│ ---          ┆ ---          ┆ ---      ┆ ---  ┆   ┆ ---          ┆ ---          ┆ ---  ┆ ---     │
│ datetime[μs, ┆ datetime[μs, ┆ str      ┆ str  ┆   ┆ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64     │
│ UTC]         ┆ UTC]         ┆          ┆      ┆   ┆ UTC]         ┆ UTC]         ┆      ┆         │
╞══════════════╪══════════════╪══════════╪══════╪═══╪══════════════╪══════════════╪══════╪═════════╡
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ c    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ p    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ p    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ p    ┆ 0.0     │
│ 06:00:00 UTC ┆ 07:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ p    ┆ 0.0     │
│ 05:00:00 UTC ┆ 06:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ …            ┆ …            ┆ …        ┆ …    ┆ … ┆ …            ┆ …            ┆ …    ┆ …       │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 05:00:00 UTC ┆ 06:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ p    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
└──────────────┴──────────────┴──────────┴──────┴───┴──────────────┴──────────────┴──────┴─────────┘

## `get_bars_spot`

In [12]:
spot = SpotInstrument(exchange="drbt", base="btc", quote="usd")

In [13]:
# Full range
io.get_bars_spot(lf_spot, spot).collect()

shape: (2_136, 8)
┌──────────────┬──────────────┬──────┬──────────────┬──────────┬───────┬─────────────┬─────────────┐
│ time_start   ┆ time_end     ┆ base ┆ px_mark      ┆ exchange ┆ quote ┆ px_bid      ┆ px_ask      │
│ ---          ┆ ---          ┆ ---  ┆ ---          ┆ ---      ┆ ---   ┆ ---         ┆ ---         │
│ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64          ┆ str      ┆ str   ┆ f64         ┆ f64         │
│ UTC]         ┆ UTC]         ┆      ┆              ┆          ┆       ┆             ┆             │
╞══════════════╪══════════════╪══════╪══════════════╪══════════╪═══════╪═════════════╪═════════════╡
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 100673.71020 ┆ drbt     ┆ usd   ┆ 99666.97310 ┆ 101680.4473 │
│ 00:00:00 UTC ┆ 01:00:00 UTC ┆      ┆ 5            ┆          ┆       ┆ 3           ┆ 07          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99951.627551 ┆ drbt     ┆ usd   ┆ 98952.11127 ┆ 100951.1438 │
│ 01:00:00 UTC ┆ 02:00:00 UTC ┆      ┆              ┆          ┆       ┆ 6           ┆ 27          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99308.625518 ┆ drbt     ┆ usd   ┆ 98315.53926 ┆ 100301.7117 │
│ 02:00:00 UTC ┆ 03:00:00 UTC ┆      ┆              ┆          ┆       ┆ 3           ┆ 73          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99450.223732 ┆ drbt     ┆ usd   ┆ 98455.72149 ┆ 100444.7259 │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆      ┆              ┆          ┆       ┆ 5           ┆ 69          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99580.563351 ┆ drbt     ┆ usd   ┆ 98584.75771 ┆ 100576.3689 │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 85          │
│ …            ┆ …            ┆ …    ┆ …            ┆ …        ┆ …     ┆ …           ┆ …           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 120682.67144 ┆ drbt     ┆ usd   ┆ 119475.8447 ┆ 121889.4981 │
│ 19:00:00 UTC ┆ 20:00:00 UTC ┆      ┆ 5            ┆          ┆       ┆ 31          ┆ 6           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 120408.70239 ┆ drbt     ┆ usd   ┆ 119204.6153 ┆ 121612.7894 │
│ 20:00:00 UTC ┆ 21:00:00 UTC ┆      ┆              ┆          ┆       ┆ 66          ┆ 14          │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 120146.76700 ┆ drbt     ┆ usd   ┆ 118945.2993 ┆ 121348.2346 │
│ 21:00:00 UTC ┆ 22:00:00 UTC ┆      ┆ 4            ┆          ┆       ┆ 34          ┆ 74          │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 119431.52657 ┆ drbt     ┆ usd   ┆ 118237.2113 ┆ 120625.8418 │
│ 22:00:00 UTC ┆ 23:00:00 UTC ┆      ┆ 7            ┆          ┆       ┆ 11          ┆ 42          │
│ 2025-03-30   ┆ 2025-03-31   ┆ btc  ┆ 119235.83369 ┆ drbt     ┆ usd   ┆ 118043.4753 ┆ 120428.1920 │
│ 23:00:00 UTC ┆ 00:00:00 UTC ┆      ┆ 4            ┆          ┆       ┆ 57          ┆ 31          │
└──────────────┴──────────────┴──────┴──────────────┴──────────┴───────┴─────────────┴─────────────┘

In [17]:
# With time filter
start = datetime(2025, 2, 1, tzinfo=timezone.utc)
end = datetime(2025, 2, 28, tzinfo=timezone.utc)
df_spot_filtered = io.get_bars_spot(lf_spot, spot, start_time=start, end_time=end).collect()
assert (df_spot_filtered["time_start"] >= start).all()
assert (df_spot_filtered["time_end"] <= end).all()
df_spot_filtered

shape: (648, 8)
┌──────────────┬──────────────┬──────┬──────────────┬──────────┬───────┬─────────────┬─────────────┐
│ time_start   ┆ time_end     ┆ base ┆ px_mark      ┆ exchange ┆ quote ┆ px_bid      ┆ px_ask      │
│ ---          ┆ ---          ┆ ---  ┆ ---          ┆ ---      ┆ ---   ┆ ---         ┆ ---         │
│ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64          ┆ str      ┆ str   ┆ f64         ┆ f64         │
│ UTC]         ┆ UTC]         ┆      ┆              ┆          ┆       ┆             ┆             │
╞══════════════╪══════════════╪══════╪══════════════╪══════════╪═══════╪═════════════╪═════════════╡
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 79299.058867 ┆ drbt     ┆ usd   ┆ 78506.06827 ┆ 80092.04945 │
│ 00:00:00 UTC ┆ 01:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 6           │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 79651.404851 ┆ drbt     ┆ usd   ┆ 78854.89080 ┆ 80447.91889 │
│ 01:00:00 UTC ┆ 02:00:00 UTC ┆      ┆              ┆          ┆       ┆ 2           ┆ 9           │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 80182.839312 ┆ drbt     ┆ usd   ┆ 79381.01091 ┆ 80984.66770 │
│ 02:00:00 UTC ┆ 03:00:00 UTC ┆      ┆              ┆          ┆       ┆ 9           ┆ 5           │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 79947.086064 ┆ drbt     ┆ usd   ┆ 79147.61520 ┆ 80746.55692 │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆      ┆              ┆          ┆       ┆ 4           ┆ 5           │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 80124.929497 ┆ drbt     ┆ usd   ┆ 79323.68020 ┆ 80926.17879 │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆      ┆              ┆          ┆       ┆ 2           ┆ 2           │
│ …            ┆ …            ┆ …    ┆ …            ┆ …        ┆ …     ┆ …           ┆ …           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 91691.356166 ┆ drbt     ┆ usd   ┆ 90774.44260 ┆ 92608.26972 │
│ 19:00:00 UTC ┆ 20:00:00 UTC ┆      ┆              ┆          ┆       ┆ 4           ┆ 7           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 92372.007934 ┆ drbt     ┆ usd   ┆ 91448.28785 ┆ 93295.72801 │
│ 20:00:00 UTC ┆ 21:00:00 UTC ┆      ┆              ┆          ┆       ┆ 4           ┆ 3           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 92481.032412 ┆ drbt     ┆ usd   ┆ 91556.22208 ┆ 93405.84273 │
│ 21:00:00 UTC ┆ 22:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 6           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 93152.991668 ┆ drbt     ┆ usd   ┆ 92221.46175 ┆ 94084.52158 │
│ 22:00:00 UTC ┆ 23:00:00 UTC ┆      ┆              ┆          ┆       ┆ 1           ┆ 4           │
│ 2025-02-27   ┆ 2025-02-28   ┆ btc  ┆ 92032.445244 ┆ drbt     ┆ usd   ┆ 91112.12079 ┆ 92952.76969 │
│ 23:00:00 UTC ┆ 00:00:00 UTC ┆      ┆              ┆          ┆       ┆ 2           ┆ 7           │
└──────────────┴──────────────┴──────┴──────────────┴──────────┴───────┴─────────────┴─────────────┘

## `get_bars_option`

In [18]:
# Pick an arbitrary option from the sampled data
row = lf_option.select(["exchange", "base", "quote", "strike", "listing", "expiry", "kind"]).head(1).collect()
opt = OptionInstrument(
    exchange=row["exchange"].item(),
    base=row["base"].item(),
    quote=row["quote"].item(),
    strike=row["strike"].item(),
    listing=row["listing"].item(),
    expiry=row["expiry"].item(),
    kind=row["kind"].item(),
)
opt

OptionInstrument(exchange='drbt', base='btc', quote='usd', strike=140000.0, listing=datetime.datetime(2025, 3, 28, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), expiry=datetime.datetime(2025, 4, 4, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), kind='c')

In [19]:
# Full range
io.get_bars_option(lf_option, opt).collect()

shape: (64, 12)
┌────────────────────┬────────────────────┬──────────┬──────┬───┬──────┬────────┬────────┬─────────┐
│ time_start         ┆ time_end           ┆ exchange ┆ base ┆ … ┆ kind ┆ iv_bid ┆ iv_ask ┆ iv_mark │
│ ---                ┆ ---                ┆ ---      ┆ ---  ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---     │
│ datetime[μs, UTC]  ┆ datetime[μs, UTC]  ┆ str      ┆ str  ┆   ┆ str  ┆ f64    ┆ f64    ┆ f64     │
╞════════════════════╪════════════════════╪══════════╪══════╪═══╪══════╪════════╪════════╪═════════╡
│ 2025-03-30         ┆ 2025-03-31         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 23:00:00 UTC       ┆ 00:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 22:00:00 UTC       ┆ 23:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 21:00:00 UTC       ┆ 22:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 20:00:00 UTC       ┆ 21:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 19:00:00 UTC       ┆ 20:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ …                  ┆ …                  ┆ …        ┆ …    ┆ … ┆ …    ┆ …      ┆ …      ┆ …       │
│ 2025-03-28         ┆ 2025-03-28         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 12:00:00 UTC       ┆ 13:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-28         ┆ 2025-03-28         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 11:00:00 UTC       ┆ 12:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-28         ┆ 2025-03-28         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 10:00:00 UTC       ┆ 11:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-28         ┆ 2025-03-28         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 09:00:00 UTC       ┆ 10:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-28         ┆ 2025-03-28         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 08:00:00 UTC       ┆ 09:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
└────────────────────┴────────────────────┴──────────┴──────┴───┴──────┴────────┴────────┴─────────┘

In [20]:
# With time filter
df_opt_filtered = io.get_bars_option(lf_option, opt, start_time=start, end_time=end).collect()
if len(df_opt_filtered) > 0:
    assert (df_opt_filtered["time_start"] > start).all()
    assert (df_opt_filtered["time_end"] < end).all()
df_opt_filtered

shape: (0, 12)
┌───────────────────┬───────────────────┬──────────┬──────┬───┬──────┬────────┬────────┬─────────┐
│ time_start        ┆ time_end          ┆ exchange ┆ base ┆ … ┆ kind ┆ iv_bid ┆ iv_ask ┆ iv_mark │
│ ---               ┆ ---               ┆ ---      ┆ ---  ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---     │
│ datetime[μs, UTC] ┆ datetime[μs, UTC] ┆ str      ┆ str  ┆   ┆ str  ┆ f64    ┆ f64    ┆ f64     │
╞═══════════════════╪═══════════════════╪══════════╪══════╪═══╪══════╪════════╪════════╪═════════╡
└───────────────────┴───────────────────┴──────────┴──────┴───┴──────┴────────┴────────┴─────────┘

## `get_target_option`

In [21]:
target = io.get_target_option(
    lf_rate, lf_spot, lf_option,
    option_exchange="drbt",
    option_base="btc",
    option_quote="usd",
    option_kind="c",
    spot_instrument=spot,
    target_time=datetime(2025, 2, 1, tzinfo=timezone.utc),
    target_delta=0.5,
    target_tenor=timedelta(days=30),
)
target

OptionInstrument(exchange='drbt', base='btc', quote='usd', strike=80000.0, listing=datetime.datetime(2025, 1, 31, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), expiry=datetime.datetime(2025, 2, 7, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), kind='c')

In [22]:
assert isinstance(target, OptionInstrument)
assert target.kind == "c"
assert target.exchange == "drbt"
assert target.base == "btc"
print(f"strike={target.strike}, listing={target.listing}, expiry={target.expiry}")

strike=80000.0, listing=2025-01-31 08:00:00+00:00, expiry=2025-02-07 08:00:00+00:00