In [23]:
%reload_ext autoreload
%autoreload 2

In [24]:
from datetime import datetime, timedelta, timezone

import polars as pl

from backtester import io, samplers
from backtester.types import SpotInstrument, OptionInstrument

## Sample data

In [25]:
t0 = datetime(2025, 1, 1, tzinfo=timezone.utc)
tf = datetime(2025, 3, 31, tzinfo=timezone.utc)
dt = timedelta(hours=1)

In [26]:
lf_rate = samplers.get_path_rate(t0, tf, dt)
paths_mark = samplers.get_paths_mark(t0, tf, dt, names=["btc"], s0=[100_000], mu=[0.10], sigma=[0.50])
lf_spot = samplers.to_bars_spot(paths_mark, exchanges="drbt", quotes="usd")
lf_option = samplers.to_bars_option(paths_mark, "drbt", "btc", "usd", rules=[samplers._WEEKLY])

In [27]:
lf_rate.collect()

shape: (2_136, 3)
┌─────────────────────────┬─────────────────────────┬──────────┐
│ time_start              ┆ time_end                ┆ rate     │
│ ---                     ┆ ---                     ┆ ---      │
│ datetime[μs, UTC]       ┆ datetime[μs, UTC]       ┆ f64      │
╞═════════════════════════╪═════════════════════════╪══════════╡
│ 2025-01-01 00:00:00 UTC ┆ 2025-01-01 01:00:00 UTC ┆ 0.05     │
│ 2025-01-01 01:00:00 UTC ┆ 2025-01-01 02:00:00 UTC ┆ 0.050008 │
│ 2025-01-01 02:00:00 UTC ┆ 2025-01-01 03:00:00 UTC ┆ 0.049946 │
│ 2025-01-01 03:00:00 UTC ┆ 2025-01-01 04:00:00 UTC ┆ 0.050078 │
│ 2025-01-01 04:00:00 UTC ┆ 2025-01-01 05:00:00 UTC ┆ 0.050038 │
│ …                       ┆ …                       ┆ …        │
│ 2025-03-30 19:00:00 UTC ┆ 2025-03-30 20:00:00 UTC ┆ 0.049305 │
│ 2025-03-30 20:00:00 UTC ┆ 2025-03-30 21:00:00 UTC ┆ 0.049202 │
│ 2025-03-30 21:00:00 UTC ┆ 2025-03-30 22:00:00 UTC ┆ 0.049255 │
│ 2025-03-30 22:00:00 UTC ┆ 2025-03-30 23:00:00 UTC ┆ 0.048931 │
│ 2025-03-30 23:00:00 UTC ┆ 2025-03-31 00:00:00 UTC ┆ 0.04882  │
└─────────────────────────┴─────────────────────────┴──────────┘

In [28]:
lf_spot.collect()

shape: (2_136, 8)
┌──────────────┬──────────────┬──────┬──────────────┬──────────┬───────┬─────────────┬─────────────┐
│ time_start   ┆ time_end     ┆ base ┆ px_mark      ┆ exchange ┆ quote ┆ px_bid      ┆ px_ask      │
│ ---          ┆ ---          ┆ ---  ┆ ---          ┆ ---      ┆ ---   ┆ ---         ┆ ---         │
│ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64          ┆ str      ┆ str   ┆ f64         ┆ f64         │
│ UTC]         ┆ UTC]         ┆      ┆              ┆          ┆       ┆             ┆             │
╞══════════════╪══════════════╪══════╪══════════════╪══════════╪═══════╪═════════════╪═════════════╡
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 100303.76078 ┆ drbt     ┆ usd   ┆ 99300.72318 ┆ 101306.7983 │
│ 00:00:00 UTC ┆ 01:00:00 UTC ┆      ┆ 8            ┆          ┆       ┆             ┆ 96          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99973.721522 ┆ drbt     ┆ usd   ┆ 98973.98430 ┆ 100973.4587 │
│ 01:00:00 UTC ┆ 02:00:00 UTC ┆      ┆              ┆          ┆       ┆ 7           ┆ 38          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99881.023358 ┆ drbt     ┆ usd   ┆ 98882.21312 ┆ 100879.8335 │
│ 02:00:00 UTC ┆ 03:00:00 UTC ┆      ┆              ┆          ┆       ┆ 4           ┆ 91          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99975.43029  ┆ drbt     ┆ usd   ┆ 98975.67598 ┆ 100975.1845 │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 93          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99309.590482 ┆ drbt     ┆ usd   ┆ 98316.49457 ┆ 100302.6863 │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆      ┆              ┆          ┆       ┆ 7           ┆ 87          │
│ …            ┆ …            ┆ …    ┆ …            ┆ …        ┆ …     ┆ …           ┆ …           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 87433.19203  ┆ drbt     ┆ usd   ┆ 86558.86011 ┆ 88307.52395 │
│ 19:00:00 UTC ┆ 20:00:00 UTC ┆      ┆              ┆          ┆       ┆             ┆ 1           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 87780.658616 ┆ drbt     ┆ usd   ┆ 86902.85203 ┆ 88658.46520 │
│ 20:00:00 UTC ┆ 21:00:00 UTC ┆      ┆              ┆          ┆       ┆             ┆ 2           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 86979.264399 ┆ drbt     ┆ usd   ┆ 86109.47175 ┆ 87849.05704 │
│ 21:00:00 UTC ┆ 22:00:00 UTC ┆      ┆              ┆          ┆       ┆ 5           ┆ 3           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 86748.28913  ┆ drbt     ┆ usd   ┆ 85880.80623 ┆ 87615.77202 │
│ 22:00:00 UTC ┆ 23:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 1           │
│ 2025-03-30   ┆ 2025-03-31   ┆ btc  ┆ 87673.573177 ┆ drbt     ┆ usd   ┆ 86796.83744 ┆ 88550.30890 │
│ 23:00:00 UTC ┆ 00:00:00 UTC ┆      ┆              ┆          ┆       ┆ 5           ┆ 9           │
└──────────────┴──────────────┴──────┴──────────────┴──────────┴───────┴─────────────┴─────────────┘

In [29]:
lf_option.collect()

shape: (20_800, 12)
┌────────────────────┬────────────────────┬──────────┬──────┬───┬──────┬────────┬────────┬─────────┐
│ time_start         ┆ time_end           ┆ exchange ┆ base ┆ … ┆ kind ┆ iv_bid ┆ iv_ask ┆ iv_mark │
│ ---                ┆ ---                ┆ ---      ┆ ---  ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---     │
│ datetime[μs, UTC]  ┆ datetime[μs, UTC]  ┆ str      ┆ str  ┆   ┆ str  ┆ f64    ┆ f64    ┆ f64     │
╞════════════════════╪════════════════════╪══════════╪══════╪═══╪══════╪════════╪════════╪═════════╡
│ 2025-03-30         ┆ 2025-03-31         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 23:00:00 UTC       ┆ 00:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 22:00:00 UTC       ┆ 23:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 21:00:00 UTC       ┆ 22:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 20:00:00 UTC       ┆ 21:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-03-30         ┆ 2025-03-30         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 19:00:00 UTC       ┆ 20:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ …                  ┆ …                  ┆ …        ┆ …    ┆ … ┆ …    ┆ …      ┆ …      ┆ …       │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 12:00:00 UTC       ┆ 13:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 11:00:00 UTC       ┆ 12:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 10:00:00 UTC       ┆ 11:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 09:00:00 UTC       ┆ 10:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ p    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 08:00:00 UTC       ┆ 09:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
└────────────────────┴────────────────────┴──────────┴──────┴───┴──────┴────────┴────────┴─────────┘

## `_get_lf_priced`

In [30]:
lf_priced = io._get_lf_priced(
    lf_rate, lf_spot, lf_option,
    option_exchange="drbt",
    option_base="btc",
    option_quote="usd",
    spot_exchange="drbt",
    spot_base="btc",
    spot_quote="usd",
)
lf_priced.collect().to_native()

shape: (20_800, 22)
┌─────────────┬────────────┬──────────┬──────┬───┬──────────┬────────────┬────────────┬────────────┐
│ time_start  ┆ time_end   ┆ exchange ┆ base ┆ … ┆ gamma    ┆ vega       ┆ theta      ┆ rho        │
│ ---         ┆ ---        ┆ ---      ┆ ---  ┆   ┆ ---      ┆ ---        ┆ ---        ┆ ---        │
│ datetime[μs ┆ datetime[μ ┆ str      ┆ str  ┆   ┆ f64      ┆ f64        ┆ f64        ┆ f64        │
│ , UTC]      ┆ s, UTC]    ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
╞═════════════╪════════════╪══════════╪══════╪═══╪══════════╪════════════╪════════════╪════════════╡
│ 2025-03-30  ┆ 2025-03-31 ┆ drbt     ┆ btc  ┆ … ┆ 0.000005 ┆ 493.255644 ┆ -20860.453 ┆ 21.582965  │
│ 23:00:00    ┆ 00:00:00   ┆          ┆      ┆   ┆          ┆            ┆ 481        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000005 ┆ 410.023731 ┆ -17172.964 ┆ 17.478381  │
│ 22:00:00    ┆ 23:00:00   ┆          ┆      ┆   ┆          ┆            ┆ 437        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000005 ┆ 444.200837 ┆ -18430.978 ┆ 19.255697  │
│ 21:00:00    ┆ 22:00:00   ┆          ┆      ┆   ┆          ┆            ┆ 31         ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000006 ┆ 544.131904 ┆ -22370.745 ┆ 24.499567  │
│ 20:00:00    ┆ 21:00:00   ┆          ┆      ┆   ┆          ┆            ┆ 228        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-03-30  ┆ 2025-03-30 ┆ drbt     ┆ btc  ┆ … ┆ 0.000005 ┆ 517.051746 ┆ -21060.113 ┆ 23.165852  │
│ 19:00:00    ┆ 20:00:00   ┆          ┆      ┆   ┆          ┆            ┆ 366        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ …           ┆ …          ┆ …        ┆ …    ┆ … ┆ …        ┆ …          ┆ …          ┆ …          │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000007 ┆ 1427.87023 ┆ -38103.392 ┆ -99.048903 │
│ 12:00:00    ┆ 13:00:00   ┆          ┆      ┆   ┆          ┆ 6          ┆ 654        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000007 ┆ 1390.8669  ┆ -36891.335 ┆ -95.985056 │
│ 11:00:00    ┆ 12:00:00   ┆          ┆      ┆   ┆          ┆            ┆ 847        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000007 ┆ 1412.92250 ┆ -37247.959 ┆ -98.151107 │
│ 10:00:00    ┆ 11:00:00   ┆          ┆      ┆   ┆          ┆ 2          ┆ 376        ┆            │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000007 ┆ 1549.50866 ┆ -40594.732 ┆ -110.78130 │
│ 09:00:00    ┆ 10:00:00   ┆          ┆      ┆   ┆          ┆ 2          ┆ 358        ┆ 3          │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
│ 2025-01-03  ┆ 2025-01-03 ┆ drbt     ┆ btc  ┆ … ┆ 0.000008 ┆ 1629.46410 ┆ -42428.201 ┆ -118.53029 │
│ 08:00:00    ┆ 09:00:00   ┆          ┆      ┆   ┆          ┆ 6          ┆ 434        ┆ 6          │
│ UTC         ┆ UTC        ┆          ┆      ┆   ┆          ┆            ┆            ┆            │
└─────────────┴────────────┴──────────┴──────┴───┴──────────┴────────────┴────────────┴────────────┘

In [31]:
# Sanity checks: prices positive, Greeks finite
df_priced = lf_priced.collect()
assert (df_priced["px_mark"] >= 0).all(), "px_mark should be non-negative"
assert df_priced["delta"].is_finite().all(), "delta should be finite"
assert df_priced["gamma"].is_finite().all(), "gamma should be finite"
assert df_priced["vega"].is_finite().all(), "vega should be finite"
assert df_priced["theta"].is_finite().all(), "theta should be finite"
assert df_priced["rho"].is_finite().all(), "rho should be finite"
print(f"priced rows: {len(df_priced):,}")

priced rows: 20,800

In [32]:
dfp: pl.DataFrame = df_priced.to_native()
dfp.filter(pl.col("px_mark") <= 0).select([
    "time_start", "time_end", "exchange", "base", "quote", "strike", "listing", "expiry", "kind", "px_mark"
])

shape: (227, 10)
┌──────────────┬──────────────┬──────────┬──────┬───┬──────────────┬──────────────┬──────┬─────────┐
│ time_start   ┆ time_end     ┆ exchange ┆ base ┆ … ┆ listing      ┆ expiry       ┆ kind ┆ px_mark │
│ ---          ┆ ---          ┆ ---      ┆ ---  ┆   ┆ ---          ┆ ---          ┆ ---  ┆ ---     │
│ datetime[μs, ┆ datetime[μs, ┆ str      ┆ str  ┆   ┆ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64     │
│ UTC]         ┆ UTC]         ┆          ┆      ┆   ┆ UTC]         ┆ UTC]         ┆      ┆         │
╞══════════════╪══════════════╪══════════╪══════╪═══╪══════════════╪══════════════╪══════╪═════════╡
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 00:00:00 UTC ┆ 01:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 01:00:00 UTC ┆ 02:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 02:00:00 UTC ┆ 03:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-01-10   ┆ 2025-01-10   ┆ drbt     ┆ btc  ┆ … ┆ 2025-01-03   ┆ 2025-01-10   ┆ c    ┆ 0.0     │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ …            ┆ …            ┆ …        ┆ …    ┆ … ┆ …            ┆ …            ┆ …    ┆ …       │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ c    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ c    ┆ 0.0     │
│ 06:00:00 UTC ┆ 07:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ c    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ c    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
│ 2025-03-28   ┆ 2025-03-28   ┆ drbt     ┆ btc  ┆ … ┆ 2025-03-21   ┆ 2025-03-28   ┆ p    ┆ 0.0     │
│ 07:00:00 UTC ┆ 08:00:00 UTC ┆          ┆      ┆   ┆ 08:00:00 UTC ┆ 08:00:00 UTC ┆      ┆         │
└──────────────┴──────────────┴──────────┴──────┴───┴──────────────┴──────────────┴──────┴─────────┘

## `get_bars_spot`

In [33]:
spot = SpotInstrument(exchange="drbt", base="btc", quote="usd")

In [34]:
# Full range
io.get_bars_spot(lf_spot, spot).collect()

shape: (2_136, 8)
┌──────────────┬──────────────┬──────┬──────────────┬──────────┬───────┬─────────────┬─────────────┐
│ time_start   ┆ time_end     ┆ base ┆ px_mark      ┆ exchange ┆ quote ┆ px_bid      ┆ px_ask      │
│ ---          ┆ ---          ┆ ---  ┆ ---          ┆ ---      ┆ ---   ┆ ---         ┆ ---         │
│ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64          ┆ str      ┆ str   ┆ f64         ┆ f64         │
│ UTC]         ┆ UTC]         ┆      ┆              ┆          ┆       ┆             ┆             │
╞══════════════╪══════════════╪══════╪══════════════╪══════════╪═══════╪═════════════╪═════════════╡
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 100303.76078 ┆ drbt     ┆ usd   ┆ 99300.72318 ┆ 101306.7983 │
│ 00:00:00 UTC ┆ 01:00:00 UTC ┆      ┆ 8            ┆          ┆       ┆             ┆ 96          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99973.721522 ┆ drbt     ┆ usd   ┆ 98973.98430 ┆ 100973.4587 │
│ 01:00:00 UTC ┆ 02:00:00 UTC ┆      ┆              ┆          ┆       ┆ 7           ┆ 38          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99881.023358 ┆ drbt     ┆ usd   ┆ 98882.21312 ┆ 100879.8335 │
│ 02:00:00 UTC ┆ 03:00:00 UTC ┆      ┆              ┆          ┆       ┆ 4           ┆ 91          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99975.43029  ┆ drbt     ┆ usd   ┆ 98975.67598 ┆ 100975.1845 │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 93          │
│ 2025-01-01   ┆ 2025-01-01   ┆ btc  ┆ 99309.590482 ┆ drbt     ┆ usd   ┆ 98316.49457 ┆ 100302.6863 │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆      ┆              ┆          ┆       ┆ 7           ┆ 87          │
│ …            ┆ …            ┆ …    ┆ …            ┆ …        ┆ …     ┆ …           ┆ …           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 87433.19203  ┆ drbt     ┆ usd   ┆ 86558.86011 ┆ 88307.52395 │
│ 19:00:00 UTC ┆ 20:00:00 UTC ┆      ┆              ┆          ┆       ┆             ┆ 1           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 87780.658616 ┆ drbt     ┆ usd   ┆ 86902.85203 ┆ 88658.46520 │
│ 20:00:00 UTC ┆ 21:00:00 UTC ┆      ┆              ┆          ┆       ┆             ┆ 2           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 86979.264399 ┆ drbt     ┆ usd   ┆ 86109.47175 ┆ 87849.05704 │
│ 21:00:00 UTC ┆ 22:00:00 UTC ┆      ┆              ┆          ┆       ┆ 5           ┆ 3           │
│ 2025-03-30   ┆ 2025-03-30   ┆ btc  ┆ 86748.28913  ┆ drbt     ┆ usd   ┆ 85880.80623 ┆ 87615.77202 │
│ 22:00:00 UTC ┆ 23:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 1           │
│ 2025-03-30   ┆ 2025-03-31   ┆ btc  ┆ 87673.573177 ┆ drbt     ┆ usd   ┆ 86796.83744 ┆ 88550.30890 │
│ 23:00:00 UTC ┆ 00:00:00 UTC ┆      ┆              ┆          ┆       ┆ 5           ┆ 9           │
└──────────────┴──────────────┴──────┴──────────────┴──────────┴───────┴─────────────┴─────────────┘

In [35]:
# With time filter
start = datetime(2025, 2, 1, tzinfo=timezone.utc)
end = datetime(2025, 2, 28, tzinfo=timezone.utc)
df_spot_filtered = io.get_bars_spot(lf_spot, spot, start_time=start, end_time=end).collect()
assert (df_spot_filtered["time_start"] > start).all()
assert (df_spot_filtered["time_end"] < end).all()
df_spot_filtered

shape: (646, 8)
┌──────────────┬──────────────┬──────┬──────────────┬──────────┬───────┬─────────────┬─────────────┐
│ time_start   ┆ time_end     ┆ base ┆ px_mark      ┆ exchange ┆ quote ┆ px_bid      ┆ px_ask      │
│ ---          ┆ ---          ┆ ---  ┆ ---          ┆ ---      ┆ ---   ┆ ---         ┆ ---         │
│ datetime[μs, ┆ datetime[μs, ┆ str  ┆ f64          ┆ str      ┆ str   ┆ f64         ┆ f64         │
│ UTC]         ┆ UTC]         ┆      ┆              ┆          ┆       ┆             ┆             │
╞══════════════╪══════════════╪══════╪══════════════╪══════════╪═══════╪═════════════╪═════════════╡
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 91353.828257 ┆ drbt     ┆ usd   ┆ 90440.28997 ┆ 92267.36654 │
│ 01:00:00 UTC ┆ 02:00:00 UTC ┆      ┆              ┆          ┆       ┆ 4           ┆             │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 90947.509726 ┆ drbt     ┆ usd   ┆ 90038.03462 ┆ 91856.98482 │
│ 02:00:00 UTC ┆ 03:00:00 UTC ┆      ┆              ┆          ┆       ┆ 9           ┆ 4           │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 90930.716818 ┆ drbt     ┆ usd   ┆ 90021.40964 ┆ 91840.02398 │
│ 03:00:00 UTC ┆ 04:00:00 UTC ┆      ┆              ┆          ┆       ┆ 9           ┆ 6           │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 90903.693734 ┆ drbt     ┆ usd   ┆ 89994.65679 ┆ 91812.73067 │
│ 04:00:00 UTC ┆ 05:00:00 UTC ┆      ┆              ┆          ┆       ┆ 7           ┆ 2           │
│ 2025-02-01   ┆ 2025-02-01   ┆ btc  ┆ 91334.337481 ┆ drbt     ┆ usd   ┆ 90420.99410 ┆ 92247.68085 │
│ 05:00:00 UTC ┆ 06:00:00 UTC ┆      ┆              ┆          ┆       ┆ 6           ┆ 6           │
│ …            ┆ …            ┆ …    ┆ …            ┆ …        ┆ …     ┆ …           ┆ …           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 82407.208768 ┆ drbt     ┆ usd   ┆ 81583.13668 ┆ 83231.28085 │
│ 18:00:00 UTC ┆ 19:00:00 UTC ┆      ┆              ┆          ┆       ┆ 1           ┆ 6           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 82409.801951 ┆ drbt     ┆ usd   ┆ 81585.70393 ┆ 83233.89997 │
│ 19:00:00 UTC ┆ 20:00:00 UTC ┆      ┆              ┆          ┆       ┆ 2           ┆ 1           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 82656.139736 ┆ drbt     ┆ usd   ┆ 81829.57833 ┆ 83482.70113 │
│ 20:00:00 UTC ┆ 21:00:00 UTC ┆      ┆              ┆          ┆       ┆ 8           ┆ 3           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 82653.881922 ┆ drbt     ┆ usd   ┆ 81827.34310 ┆ 83480.42074 │
│ 21:00:00 UTC ┆ 22:00:00 UTC ┆      ┆              ┆          ┆       ┆ 3           ┆ 2           │
│ 2025-02-27   ┆ 2025-02-27   ┆ btc  ┆ 82876.257795 ┆ drbt     ┆ usd   ┆ 82047.49521 ┆ 83705.02037 │
│ 22:00:00 UTC ┆ 23:00:00 UTC ┆      ┆              ┆          ┆       ┆ 7           ┆ 3           │
└──────────────┴──────────────┴──────┴──────────────┴──────────┴───────┴─────────────┴─────────────┘

## `get_bars_option`

In [36]:
# Pick an arbitrary option from the sampled data
row = lf_option.select(["exchange", "base", "quote", "strike", "listing", "expiry", "kind"]).head(1).collect()
opt = OptionInstrument(
    exchange=row["exchange"].item(),
    base=row["base"].item(),
    quote=row["quote"].item(),
    strike=row["strike"].item(),
    listing=row["listing"].item(),
    expiry=row["expiry"].item(),
    kind=row["kind"].item(),
)
opt

OptionInstrument(exchange='drbt', base='btc', quote='usd', strike=130000.0, listing=datetime.datetime(2025, 1, 3, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), expiry=datetime.datetime(2025, 1, 10, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), kind='c')

In [37]:
# Full range
io.get_bars_option(lf_option, opt).collect()

shape: (168, 12)
┌────────────────────┬────────────────────┬──────────┬──────┬───┬──────┬────────┬────────┬─────────┐
│ time_start         ┆ time_end           ┆ exchange ┆ base ┆ … ┆ kind ┆ iv_bid ┆ iv_ask ┆ iv_mark │
│ ---                ┆ ---                ┆ ---      ┆ ---  ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---     │
│ datetime[μs, UTC]  ┆ datetime[μs, UTC]  ┆ str      ┆ str  ┆   ┆ str  ┆ f64    ┆ f64    ┆ f64     │
╞════════════════════╪════════════════════╪══════════╪══════╪═══╪══════╪════════╪════════╪═════════╡
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 08:00:00 UTC       ┆ 09:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 09:00:00 UTC       ┆ 10:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 10:00:00 UTC       ┆ 11:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 11:00:00 UTC       ┆ 12:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-03         ┆ 2025-01-03         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 12:00:00 UTC       ┆ 13:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ …                  ┆ …                  ┆ …        ┆ …    ┆ … ┆ …    ┆ …      ┆ …      ┆ …       │
│ 2025-01-10         ┆ 2025-01-10         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 03:00:00 UTC       ┆ 04:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-10         ┆ 2025-01-10         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 04:00:00 UTC       ┆ 05:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-10         ┆ 2025-01-10         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 05:00:00 UTC       ┆ 06:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-10         ┆ 2025-01-10         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 06:00:00 UTC       ┆ 07:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
│ 2025-01-10         ┆ 2025-01-10         ┆ drbt     ┆ btc  ┆ … ┆ c    ┆ 0.99   ┆ 1.01   ┆ 1.0     │
│ 07:00:00 UTC       ┆ 08:00:00 UTC       ┆          ┆      ┆   ┆      ┆        ┆        ┆         │
└────────────────────┴────────────────────┴──────────┴──────┴───┴──────┴────────┴────────┴─────────┘

In [38]:
# With time filter
df_opt_filtered = io.get_bars_option(lf_option, opt, start_time=start, end_time=end).collect()
if len(df_opt_filtered) > 0:
    assert (df_opt_filtered["time_start"] > start).all()
    assert (df_opt_filtered["time_end"] < end).all()
df_opt_filtered

shape: (0, 12)
┌───────────────────┬───────────────────┬──────────┬──────┬───┬──────┬────────┬────────┬─────────┐
│ time_start        ┆ time_end          ┆ exchange ┆ base ┆ … ┆ kind ┆ iv_bid ┆ iv_ask ┆ iv_mark │
│ ---               ┆ ---               ┆ ---      ┆ ---  ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---     │
│ datetime[μs, UTC] ┆ datetime[μs, UTC] ┆ str      ┆ str  ┆   ┆ str  ┆ f64    ┆ f64    ┆ f64     │
╞═══════════════════╪═══════════════════╪══════════╪══════╪═══╪══════╪════════╪════════╪═════════╡
└───────────────────┴───────────────────┴──────────┴──────┴───┴──────┴────────┴────────┴─────────┘

## `get_target_option`

In [39]:
target = io.get_target_option(
    lf_rate, lf_spot, lf_option,
    option_exchange="drbt",
    option_base="btc",
    option_quote="usd",
    option_kind="c",
    spot_instrument=spot,
    target_time=datetime(2025, 2, 1, tzinfo=timezone.utc),
    target_delta=0.5,
    target_tenor=timedelta(days=30),
)
target

OptionInstrument(exchange='drbt', base='btc', quote='usd', strike=92000.0, listing=datetime.datetime(2025, 1, 31, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), expiry=datetime.datetime(2025, 2, 7, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), kind='c')

In [40]:
assert isinstance(target, OptionInstrument)
assert target.kind == "c"
assert target.exchange == "drbt"
assert target.base == "btc"
print(f"strike={target.strike}, listing={target.listing}, expiry={target.expiry}")

strike=92000.0, listing=2025-01-31 08:00:00+00:00, expiry=2025-02-07 08:00:00+00:00